server:
  servlet:
    context-path: /zuul01
  port: 9020
spring:
  application:
    name: zuul
eureka:
  instance:
    instance-id: zuul01
    prefer-ip-address: true
    metadata-map:
      zone: zone-1
  client:
    prefer-same-zone-eureka: true
    region: guangzhou
    availability-zones:
      guangzhou: zone-1,zone-2
    service-url:
      zone-1: http://localhost:8080/eureka01/eureka/
      zone-2: http://localhost:8081/eureka02/eureka/
zuul:
  routes:
    # 路由映射
    customer.serviceId: servicecustomer
    customer.path: /customer/**
  # 忽略所有
  ignored-services: "*"
  #统一公共前缀
  prefix: /cloud
  #忽略真实的服务
  #ignored-services: servicecustomer



